### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [AhmadMaleki/fa-utils#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by AhmadMaleki** [comment]
Yes ofcourse I'm interested! Your pull request is so welcome.

**Comment by geopic** [comment]
Great, I'll start on it now.

**Comment by AhmadMaleki** [comment]
Thank you @geopic I merged your commit and will publish to npm soon.
